# -*- coding: utf-8 -*-
"""magic- data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1-elkwhi2u0Mbv9K0ioFzqOdmIQRugB

The dataset is provided as a zip file. We need to extract it first to access the data. The error message indicates the zip file contains `magic04.data` and `magic04.names`.
"""

# Unzip the file to extract its contents
!unzip /content/magic+gamma+telescope.zip -d /content/

"""Now that the files are extracted, we can read the `magic04.data` file into a pandas DataFrame. Since this file does not have a header, we need to specify `header=None`."""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#loading of data
df=pd.read_csv("/content/magic04.data", header=None)
df.head()

df.info()

df.describe()

# Check for missing values in each column
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values)

df[10].unique()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
sns.countplot(x=df[10], hue=df[10], palette='viridis', legend=False)
plt.title('Distribution of Column 10 (Target Variable)')
plt.xlabel('Class Label')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 6))
sns.histplot(df[0], bins=50, kde=True)
plt.title('Distribution of Column 0')
plt.xlabel('Column 0 Value')
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df[0], y=df[1], alpha=0.5)
plt.title('Scatter Plot of Column 0 vs. Column 1')
plt.xlabel('Column 0 Value')
plt.ylabel('Column 1 Value')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# Calculate the correlation matrix for numerical columns
# Exclude the last column (column 10) as it is categorical
correlation_matrix = df.iloc[:, :10].corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""### Prepare Data for Classification

First, we need to separate the features (X) from the target variable (y). In our dataset, columns 0-9 are the features, and column 10 is the target. Since the target variable is categorical ('g' and 'h'), we will use `LabelEncoder` to convert these into numerical format (0 and 1).
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Separate features (X) and target (y)
X = df.iloc[:, :10]  # Features are columns 0 to 9
y = df.iloc[:, 10]   # Target is column 10

# Encode the target variable 'g' and 'h' to numerical (0 and 1)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Original target labels:", y.unique())
print("Encoded target labels:", label_encoder.classes_)
print("Shape of features (X):", X.shape)
print("Shape of encoded target (y_encoded):", y_encoded.shape)

"""Next, we split the data into training and testing sets. This allows us to train our model on one portion of the data and evaluate its performance on unseen data, which helps in assessing its generalization capability."""

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

"""### Feature Scaling

It is often beneficial to scale features so that they have similar ranges. This prevents features with larger values from dominating the learning process. We will use `StandardScaler` to transform the data such that it has a mean of 0 and a standard deviation of 1.
"""

from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and test data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Features scaled successfully!")
print(f"Shape of scaled training features: {X_train_scaled.shape}")
print(f"Shape of scaled testing features: {X_test_scaled.shape}")

"""### Train a Classification Model

For a binary classification task like this, a Logistic Regression model is a good starting point due to its simplicity and interpretability. We will train the model on the training data.
"""

from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model
# Set max_iter for convergence as per scikit-learn warning suggestions for some datasets
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_scaled, y_train)

"""### Evaluate Model Performance

Finally, we evaluate the trained model on the test set using common classification metrics like accuracy, precision, recall, and F1-score. This will give us an idea of how well the model performs.
"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)
print("\nConfusion Matrix:")
print(conf_matrix)
